version: '3.7'

services:
  alfred_controller_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_controller_service:latest
    container_name: alfred_controller_service
    hostname: alfred_controller_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - ALFRED_FLOWERCARE_SERVICE=${ALFRED_FLOWERCARE_SERVICE}
      - ALFRED_COMMUTE_SERVICE=${ALFRED_COMMUTE_SERVICE}
      - ALFRED_NETATMO_SERVICE=${ALFRED_NETATMO_SERVICE}
      - ALFRED_DYSON_SERVICE=${ALFRED_DYSON_SERVICE}
      - ALFRED_LIGHTS_SERVICE=${ALFRED_LIGHTS_SERVICE}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  
networks:
  alfred:
    name: alfred
    driver: bridge
