version: "3.7"

services:
  alfred_hls_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_hls_service:latest
    container_name: alfred_hls_service
    hostname: alfred_hls_service
    restart: always
    networks:
      - alfred
    command: npm run start
    volumes:
      - media:/home/nodejs/app/media
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - APP_ROLE_ID=${APP_ROLE_ID}
      - APP_TOKEN=${APP_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  media:

networks:
  alfred:
    name: alfred
    driver: bridge
