version: '3.7'

services:
  alfred_hls_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_hls_service:latest
    container_name: alfred_hls_service
    hostname: alfred_hls_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - '3980:3978'
    extra_hosts:
      - 'timescaledb:192.168.85.12'

networks:
  alfred:
    name: alfred
    driver: bridge
