version: '3.5'

services:
  alfred_health_service:
    build: .
    image: alfred_health_service:latest
    container_name: alfred_health_service
    restart: always
    ports:
      - '3982:3978'
    hostname: alfred_health_service
    networks:
      - alfred
    command: npm run prod

networks:
  alfred:
    name: alfred
    driver: bridge
