version: '3.5'

services:
  alfred_health_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_health_service:latest
    container_name: alfred_health_service
    hostname: alfred_health_service
    restart: always
    ports:
      - '3982:3978'
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  alfred:
    name: alfred
    driver: bridge
