filebeat.inputs:
  - type: docker
    containers:
      path: "/usr/share/dockerlogs/data"
      stream: "stdout"
      ids:
        - "*"
      cri.parse_flags: true
      combine_partial: true
      exclude_files: ['\.gz$']

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

  processors:
    # decode the message field (sub JSON document) if JSONencoded, then maps it's fields to elasticsearch fields
    - decode_json_fields:
        fields: ["message"]
        target: ""
    # overwrite existing target elasticsearch fields while decoding json fields
        overwrite_keys: true
    - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELK_HOST:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  template:
    name: "filebeat"
    path: "fields.yml"
    overwrite: false
  protocol: "http"
