version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5001
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["http://alfredserver:81"]
    Access-Control-Allow-Methods: ["HEAD", "GET", "OPTIONS", "DELETE"]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
