version: '3.7'

services:
  alfred_tp_link_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_tp_link_service:latest
    container_name: alfred_tp_link_service
    hostname: alfred_tp_link_service
    restart: always
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - ALFRED_WEATHER_SERVICE=${ALFRED_WEATHER_SERVICE}
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - alfred

networks:
  alfred:
    name: alfred
    driver: bridge
