version: '3.5'

services:
  alfred_tp_link_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_tp_link_service:latest
    container_name: alfred_tp_link_service
    hostname: alfred_tp_link_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  alfred:
    name: alfred
    driver: bridge
