version: "3.9"

services:
  alfred_ring_data_collector_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_ring_data_collector_service:latest
    container_name: alfred_ring_data_collector_service
    hostname: alfred_ring_data_collector_service
    restart: always
    networks:
      - alfred
    command: node lib/server/server.js
    volumes:
      - media_library:/home/nodejs/app/media
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - APP_ROLE_ID=${APP_ROLE_ID}
      - APP_TOKEN=${APP_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

volumes:
  media_library:
    external: true

networks:
  alfred:
    name: alfred
    driver: bridge
