version: "3.7"

services:
  alfred_flower_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_house_flowers_service
    container_name: alfred_house_flowers_service
    hostname: alfred_house_flowers_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - APP_ROLE_ID=${APP_ROLE_ID}
      - APP_TOKEN=${APP_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  alfred:
    name: alfred
    driver: bridge
