version: '3.5'

services:
  noip:
    build: .
    hostname: no-ip
    container_name: no-ip
    volumes:
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      - server

networks:
  server:
    name: server
    driver: bridge
