version: '3.5'

services:
  noip:
    image: coppit/no-ip
    volumes:
      - .:/config
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      - server

networks:
  server:
    name: server
    driver: bridge
