version: '3.7'

services:
  noip:
    build: .
    hostname: no-ip
    container_name: no-ip
    volumes:
      - /etc/localtime:/etc/localtime
      - data:/config 
    restart: always
    networks:
      - server

volumes:
  data:

networks:
  server:
    name: server
    driver: bridge
