version: '3.5'

services:
  noip:
    image: coppit/no-ip
    hostname: no-ip
    container_name: no-ip
    volumes:
      - /config/noip.conf:/config/noip.conf
      - /etc/localtime:/etc/localtime
    restart: always
    networks:
      - server

networks:
  server:
    name: server
    driver: bridge
