version: '3.7'

services:
  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    hostname: openvpn
    ports:
      - "3000:1194/udp"
    restart: always
    volumes:
      - data:/etc/data
    networks:
      - server

volumes:
  data:

networks:
  server:
    name: server
    driver: bridge