version: '3.7'

services:
  alfred_lights_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_lights_service:latest
    container_name: alfred_lights_service
    hostname: alfred_lights_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - ALFRED_CONTROLLER_SERVICE=${ALFRED_CONTROLLER_SERVICE}
      - VAULT_URL=${VAULT_URL}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  alfred:
    name: alfred
    driver: bridge
