version: '3.7'

services:
  alfred_lights_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_lights_service:latest
    container_name: alfred_lights_service
    hostname: alfred_lights_service
    restart: always
    networks:
      - alfred
    command: node lib/server/server.js
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - APP_ROLE_ID=${APP_ROLE_ID}
      - APP_TOKEN=${APP_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
      - ALFRED_WEATHER_SERVICE=${ALFRED_WEATHER_SERVICE}
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

networks:
  alfred:
    name: alfred
    driver: bridge
