version: '3.5'

services:
  alfred_lights_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_lights_service:latest
    container_name: alfred_lights_service
    restart: always
    hostname: alfred_lights_service
    networks:
      - alfred
    ports:
      - '3983:3978'
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}

networks:
  alfred:
    name: alfred
    driver: bridge
