version: '3.7'

services:
  alfred_dyson_data_collector_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_dyson_data_collector_service:latest
    container_name: alfred_dyson_data_collector_service
    hostname: alfred_dyson_data_collector_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
      - TRACE_LEVEL=${TRACE_LEVEL}
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

networks:
  alfred:
    name: alfred
    driver: bridge
