version: "3.7"

services:
  alfred_flowercare_data_collector_service:
    image: ${DOCKER_REGISTERY_URL}/alfred_flowercare_data_collector_service
    container_name: alfred_flowercare_data_collector_service
    hostname: alfred_flowercare_data_collector_service
    restart: always
    networks:
      - alfred
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - APP_ROLE_ID=${APP_ROLE_ID}
      - APP_TOKEN=${APP_TOKEN}
      - NO_SCHEDULE=${NO_SCHEDULE}
      - NO_SCAN=${NO_SCAN}
      - ZONE=${ZONE}
      - TRACE_LEVEL=${TRACE_LEVEL}
      - SERVER_NAME=${SERVER_NAME}
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  alfred:
    name: alfred
    driver: bridge
