version: '3.7'

services:
  alfred_flowercare_data_collector_service:
    build: .
    container_name: alfred_flowercare_data_collector_service
    hostname: alfred_flowercare_data_collector_service
    restart: always
    network_mode: 'host'
    privileged: true
    command: npm run start
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - MOCK=${MOCK}
      - PORT=${PORT}
      - VAULT_URL=${VAULT_URL}
      - VAULT_TOKEN=${VAULT_TOKEN}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
