version: '3.7'
services:
  influxdb_container:
    image: quay.io/influxdb/influxdb:2.0.0-rc
    environment:
      INFLUX_TOKEN: ${INFLUX_TOKEN}
    container_name: influxdb
    hostname: influxdb
    restart: always
    networks:
      - alfred
    ports:
      - 8086:8086
    volumes:
      - data:/root/.influxdbv2
      - bolt:/var/influx/bolt
      - engine:/var/influx/engine
    labels:
      com.centurylinklabs.watchtower.enable: 'true'

  telegraf_container:
    image: telegraf
    container_name: telegraf
    restart: always
    extra_hosts:
      - 'influxdb:192.168.1.12'
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_ORG: ${INFLUX_ORG}
      INFLUX_BUCKET: mongodb
      MONGO_STRING_CONNECTION: ${MONGO_STRING_CONNECTION}
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro

volumes:
  data:
  bolt:
  engine:

networks:
  alfred:
    name: alfred
    driver: bridge
